# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3fdb79c45e8ca49d7b8804b1051104baf7673a3f1aac28ce0ea31f526cb9b8c321d3097cd2d525ebf1412cb6742200107e4e78c6b1317cffb0d2c66d716b7beb

test:
  secret_key_base: f1fc7516099e809b83408cd4cb46ddc32ed9647e0a0726ab1dac349374e6a3c9eedf8e0545821bb0d40a33236c20284cf2b69fdf95e33d59ed8615781eaf2b68

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
